HrWebb/Models/JobOffer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace HrWebb.Models
{
    public class JobOffer: IValidatableObject
    {
        public int Id { get; set; }
        [Display(Name="Job title")]
        [Required]
        public string JobTitle { get; set; }
        public virtual Company Company { get; set; }
        public virtual int CompanyId { get; set; }
        [Display(Name ="Salary from")]
        [Range(1, int.MaxValue, ErrorMessage = "Must be greater than 0")]
        public decimal? SalaryFrom { get; set; }
        [Display (Name ="Salary to")]
        [Range(1,int.MaxValue,ErrorMessage ="Must be greater than 0")]
        public decimal? SalaryTo { get; set; }
        public DateTime Created { get; set; }
        public string Location { get; set; }
        [Required]
        [MinLength(100)]
        public string Description { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode =true,DataFormatString ="{0:yyy-MM-dd}")]
        [Display(Name="Valid until")]
        [CurrentDate(ErrorMessage ="Date is past")]
        public DateTime? ValidUntil { get; set; }
        public List<JobApplication> JobApplications { get; set; } = new List<JobApplication>();

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if(SalaryFrom>SalaryTo)
            {
                yield return
                    new ValidationResult(errorMessage: "Salary to must be greater than Salary from",memberNames: new[] { "SalaryTo" });
            }
        }
    }
}

HrWebb/Controllers/JobApplicationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HrManagement.Helpers;
using HrWebb.EntityFramwork;
using HrWebb.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace HrWebb.Controllers
{
    [Route("[controller]/[action]")]
    public class JobApplicationController : Controller
    {
        private readonly DataContext _context;
        private readonly FileUploader fileUploader;
        public JobApplicationController(IConfiguration configuration, DataContext context)
        {
            _context = context;
            fileUploader = new FileUploader(configuration.GetSection("StorageConnectionString").Get<string>());

        }
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public async Task<ActionResult> Create(int k)
        {
            JobApplication jobApplication = new JobApplication();
            jobApplication.OfferId = k;
            return View(jobApplication);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(JobApplication model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            _context.JobApplications.Add(model);
            await _context.SaveChangesAsync();
            await fileUploader.UploadFile(model.File);
            return RedirectToAction("Index", "JobOffer");
        }
        [HttpGet]
        public IActionResult Details(int id)
        {
            JobApplication jobApplication =_context.JobApplications.ToList().Find(o => o.Id == id);
            return View(jobApplication);
        }
    }
}

HrWebb/Controllers/JobOfferController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HrWebb.EntityFramwork;
using HrWebb.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HrWebb.Controllers
{
    [Route("[controller]/[action]")]
    public class JobOfferController : Controller
    {
        private readonly DataContext _context;
        public JobOfferController(DataContext context)
        {
            _context = context;
        }
        [HttpGet]
        public IActionResult Details(int id)
        {
            var offer = _context.JobOfers.Include(jobOffer => jobOffer.Company).FirstOrDefault(o => o.Id == id);
            if (offer == null) return NotFound();
            return View(offer);
        }
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
                return BadRequest();
            var offer = _context.JobOfers.ToList().Find(j => j.Id == id);
            if (offer == null) return NotFound();
            return View(offer);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(JobOffer model)
        {
            var offer = _context.JobOfers.ToList().Find(j => j.Id == model.Id);
            offer.JobTitle = model.JobTitle;
            offer.Description = model.Description;
            _context.Update(offer);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", new { id = model.Id });
        }
        [HttpPost]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
                return BadRequest();
            var offer = _context.JobOfers.ToList().Find(j => j.Id == id);
            _context.JobOfers.Remove(offer);
            _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<ActionResult> Create()
        {
            var model = new JobOfferCreateView
            {
                Companies = _context.Companies.ToList()
            };
            model.Created = DateTime.Now;
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(JobOfferCreateView model)
        {
            if (!ModelState.IsValid)
            {
                model.Companies = _context.Companies.ToList();
                return View(model);
            }

            JobOffer jobOffer = new JobOffer
            {
                CompanyId = model.CompanyId,
                Description = model.Description,
                JobTitle = model.JobTitle,
                Location = model.Location,
                SalaryFrom = model.SalaryFrom,
                SalaryTo = model.SalaryTo,
                ValidUntil = model.ValidUntil,
                Created = DateTime.Now
            };
            _context.JobOfers.Add(jobOffer);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public OffersPage GetOffers([FromQuery(Name = "search")] string searchString,int pageNumber)
        {
            IQueryable<JobOffer> preResult;
            if(String.IsNullOrEmpty(searchString))
            {
                preResult = _context.JobOfers;
            }
            else
            {
                preResult = _context.JobOfers.Where(jobOffer => jobOffer.JobTitle.Contains(searchString));
            }


            int pageSize = 4;
            int numberOfOffers = preResult.Count();
            int numberOfPages = (int)Math.Ceiling(((double)numberOfOffers) / ((double)pageSize));

            List<JobOffer> resultList = preResult.OrderBy(jobOffer => jobOffer.JobTitle).Skip((pageSize * (pageNumber-1))).Take(pageSize).Include(jobOffer => jobOffer.Company).ToList();
            OffersPage offersPage =new OffersPage(numberOfPages, pageNumber, resultList);
            return offersPage;
        }
        [HttpGet]
        public IEnumerable<JobApplication> GetApplications(int id)
        {
            return _context.JobApplications.Where(jobApplication=>jobApplication.OfferId==id).ToList();
        }
    }
}

HrWebb/Views/JobOffer/Create.cshtml
@model JobOfferCreateView
@{
    ViewData["Title"] = "Create";
}
<div class="row page-box">
    <div class="col-sm-12">
        <h2>New Job Offer</h2>
        @using (Html.BeginForm("Create"))
        {
            @Html.AntiForgeryToken()
            <div class="form-group">
                @Html.LabelFor(m => m.JobTitle)
                @Html.EditorFor(m => m.JobTitle, new { htmlAttributes = new { @class = "form-control", @data_bind = "value: jobName" } })
                @Html.ValidationMessageFor(m => m.JobTitle, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Company)
                <select class="form-control"
                        data-bind="options: companiesArray,
                        optionsText: function(item) {
                            return item.name;
                        },
                        value: selectedCompany"></select>
                @Html.HiddenFor(m => m.CompanyId, new { @data_bind = "value: selectedCompany().id" })
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Location)
                @Html.EditorFor(m => m.Location, new { htmlAttributes = new { @class = "form-control", @data_bind = "value: place" } })
                @Html.ValidationMessageFor(m => m.Location, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.SalaryFrom, "Salary From")
                <div class="input-group">
                    <span class="input-group-addon">PLN</span>
                    @Html.EditorFor(m => m.SalaryFrom, new { htmlAttributes = new { @class = "form-control", placeholder = "From" } })
                    <span class="input-group-addon">.00</span>
                </div>
                @Html.ValidationMessageFor(m => m.SalaryFrom, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.SalaryTo, "Salary To")
                <div class="input-group">
                    <span class="input-group-addon">PLN</span>
                    @Html.EditorFor(m => m.SalaryTo, new { htmlAttributes = new { @class = "form-control", placeholder = "To", @data_bind = "value: salaryTo" } })
                    <span class="input-group-addon">.00</span>
                </div>
                @Html.ValidationMessageFor(m => m.SalaryTo, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.ValidUntil)
                <div class="input-group">
                    @Html.EditorFor(m => m.ValidUntil, new { htmlAttributes = new { @class = "form-control", @data_bind = "value: date" }, type = "Date" })
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
                @Html.ValidationMessageFor(m => m.ValidUntil, "", new { @class = "text-danger" })
            </div>
            <div>
                @Html.LabelFor(m => m.Description)
                @Html.TextAreaFor(m => m.Description, new { @class = "form-control", placeholder = "Enter description", @data_bind = "value: description" })
                @Html.ValidationMessageFor(m => m.Description, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Create</button>
            </div>
        }
    </div>
</div>
<h3>Preview:</h3>
<div class="row page-box">
    <h1 data-bind="text: jobName"></h1>
    <div class="col-sm-8">
        <div class="offer-description" id="previewMarkDown">
            <p data-bind="text: description"></p>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="offer-details">
            <div>
                <label>Company</label>
                <span data-bind="text: selectedCompany().name"></span>
            </div>
            <div data-bind="visible: place">
                <label>Location</label>
                <span data-bind="text: place"></span>
            </div>
            <div data-bind="visible: salaryTo">
                <label>Salary to</label>
                <span data-bind="text: salaryTo">/span>
            </div>
            <div>
                <label>Created:</label>
                <span>@Model.Created</span>
            </div>

            <div data-bind="visible: date">
                <label>Valid</label>
                <span data-bind="text: date"></span>
            </div>
        </div>
    </div>
</div>

<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.0.3.min.js"></script>
<script src="~/lib/knockout/knockout-min.js"></script>
<script>

    $(document).ready(function () {
        var ViewModel = function () {
            this.jobName = ko.observable();
            this.description = ko.observable();
            this.place = ko.observable();
            this.salaryTo = ko.observable();
            this.date = ko.observable();

            var jCompanies = @Html.Raw(Json.Serialize(Model.Companies));
            this.companiesArray = ko.observableArray(jCompanies);
            this.selectedCompany = ko.observable(jCompanies[0]);
        };

        ko.applyBindings(new ViewModel());
    });

</script>

HrWebb/Views/JobOffer/Details.cshtml
@model JobOffer
@{ ViewBag.Title = "Offer";}

<div class="row page-box">
    <h1>@Model.JobTitle</h1>
    <div class="col-sm-8">
        <div class="offer-description" id="previewMarkDown">
            @Model.Description
        </div>
    </div>
    <div class="col-sm-4">
        <div class="offer-details">
            <div>
                <label>Company</label>
                <span>@Model.Company.Name</span>
            </div>
            <div>
                <label>Location</label>
                <span>@Model.Location</span>
            </div>
            @if (Model.SalaryFrom.HasValue)
            {
                <div>
                    <label>Salary to</label>
                    <span>@Model.SalaryTo</span>
                </div>
            }
            <div>
                <label>Crated:</label>
                <span>@Model.Created</span>
            </div>
            @if (Model.ValidUntil.HasValue)
            {
                <div>
                    <label>Valid</label>
                    <span>@Model.ValidUntil.Value.Subtract(DateTime.Now).Days days (@Model.ValidUntil)</span>
                </div>
            }
            <div>
                @Html.ActionLink("Apply Now", "Create", "JobApplication", new { k = Model.Id }, new { @class = "btn btn-primary" })
                @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "btn btn-primary" })
            </div>
            <div>
                @using (Html.BeginForm("Delete", "JobOffer", new { Model.Id }, FormMethod.Post, null, new { style = "display:inline;" }))
                {
                    @Html.AntiForgeryToken()
                    <button type="submit" class="btn btn-danger">Delete</button>
                }
            </div>
        </div>
    </div>
    <table id="applicationsTable" class="table table-striped table hover">
        <thread class="thread-dark">
            <tr>
                <th scope="col">First Name</th>
                <th scope="col">Last Name</th>
                <th scope="col">Email</th>
                <th scope="col">Phone</th>
            </tr>
        </thread>
    </table>
    @Html.ActionLink("Go back to Job Offers", "Index", "JobOffer", null, new { @class = "btn btn-primary" })
</div>
<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.0.3.min.js"></script>
<script>
    var uri = 'GetApplications?id=' +@Model.Id;
    $(document).ready(function () {
        $.getJSON(uri)
            .done(function (data) {
                $.each(data, function (key, item) {
                    $('#applicationsTable').find("tbody")
                        .append($('<tr>')
                            .append($('<td>').text(item.firstName))
                            .append($('<td>').text(item.lastName))
                            .append($('<td>').text(item.emailAddress))
                            .append($('<td>').text(item.phoneNumer)))
                });
            });
    }
    );
</script>
  

HrWebb/Views/JobOffer/Edit.cshtml
@model JobOffer
@{ 
    ViewBag.Title = "Edit";
}
<div class="row">
    <div class="col-sm12"> 
        <h2>Edit Job Offer</h2>
        @using (Html.BeginForm("Edit"))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(m=>m.Id)
            <div class="form-group">
                @Html.LabelFor(m=>m.JobTitle)
                @Html.EditorFor(m=>m.JobTitle,new { htmlAtributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(m=>m.JobTitle)
            </div>
            <div class="form-group">
                @Html.LabelFor(m=>m.Description)
                @Html.TextAreaFor(m=>m.Description,new  {@class="form-control",placeholder="Enter Description"})
                @Html.ValidationMessageFor(m => m.Description, "", new { @class="text-danger" })
            </div>
            <button type="submit" class="btn btn-primary">save</button>
        }
    </div>
</div>

HrWebb/Views/JobOffer/Index.cshtml
<div class="row page-box">
    <div class="col-sm-12">
        <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.0.3.min.js"></script>
        <script>
            var uri = 'GetOffers';

            $(document).ready(function () {

                $('#jobOffersTable').on('click', '.footerContent a', function (e) {
                    var pageNumber = parseInt($(this).html());
                    var search = $('#search').val();
                    getOffers(search,pageNumber );
                });
                getOffers('', 1);
            });


            function searchForOffers() {
                var search = $('#search').val();
                getOffers(search, 1);
            }

            function getOffers(search, page) {
                $.getJSON(uri + '?search=' + search + '&pageNumber=' + page)
                    .done(function (data) {

                        var $table = $('#jobOffersTable');

                        $table.find("tbody").html("");
                        $.each(data.jobOffers, function (key, item) {
                            var $row = $('<tr>');
                            $row.append($('<td>').html(
                                "<a href=\"" + "/JobOffer/Details?id=" + item.id + "\" >"
                                + item.jobTitle
                                + "<\a>"));
                            $row.append($('<td>').text(item.company.name));
                            $row.append($('<td>').text(item.location));
                            var date = new Date(Date.parse(item.created));
                            var day = date.getDate();
                            var month = date.getMonth() + 1;
                            var year = date.getFullYear();
                            $row.append($('<td>').text(day + '/' + month + '/' + year));
                            $table.find("tbody").append($row);
                        });

                        var currentPage = data.pageNumber;
                        var totalPage = data.numberOfPages;
                        var $footer = $('<tr/>');
                        var $footerTD = $('<td/>').attr('colspan', 4).addClass('footerContent');

                        if (totalPage > 0) {
                            for (var i = 1; i <= totalPage; i++) {
                                var $page = $('<span/>').addClass((i == currentPage) ? "current" : "");
                                $page.html((i == currentPage) ? i : "<a href='#'>" + i + "</a>");
                                $footerTD.append($page);
                            }
                            $footer.append($footerTD);
                        }
                        $table.append($footer);
                    });
            }
        </script>

        <h2>Job Offers</h2>

        <div class="input-group col-md-12" style="margin-bottom: 14px">
            <input type="text" class="form-control" placeholder="Search by offer tittle.."
                   name="search" id="search" />
            <span class="input-group-btn">
                <button class="btn btn-info" type="button" onclick="searchForOffers()">
                    <i class="glyphicon glyphicon-search"></i>
                </button>

            </span>
        </div>

        <table id="jobOffersTable" class="table table-striped table-hover">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Job Title</th>
                    <th scope="col">Company</th>
                    <th scope="col">Location</th>
                    <th scope="col">Created</th>
                </tr>
            </thead>
            <tbody />
        </table>

        @Html.ActionLink("Create job offer", "Create", "JobOffer", null, new { @class = "btn btn-primary" })
    </div>
</div>